#define _ARLK_NITE_
//#define _ARLK_KSDK_

#ifdef _ARLK_KSDK_
#ifndef _NUI_SKELETON_POSITION_INDEX_
#define _NUI_SKELETON_POSITION_INDEX_
typedef
	enum _NUI_SKELETON_POSITION_INDEX
{	NUI_SKELETON_POSITION_HIP_CENTER	= 0,
NUI_SKELETON_POSITION_SPINE	= ( NUI_SKELETON_POSITION_HIP_CENTER + 1 ) ,
NUI_SKELETON_POSITION_SHOULDER_CENTER	= ( NUI_SKELETON_POSITION_SPINE + 1 ) ,
NUI_SKELETON_POSITION_HEAD	= ( NUI_SKELETON_POSITION_SHOULDER_CENTER + 1 ) ,
NUI_SKELETON_POSITION_SHOULDER_LEFT	= ( NUI_SKELETON_POSITION_HEAD + 1 ) ,
NUI_SKELETON_POSITION_ELBOW_LEFT	= ( NUI_SKELETON_POSITION_SHOULDER_LEFT + 1 ) ,
NUI_SKELETON_POSITION_WRIST_LEFT	= ( NUI_SKELETON_POSITION_ELBOW_LEFT + 1 ) ,
NUI_SKELETON_POSITION_HAND_LEFT	= ( NUI_SKELETON_POSITION_WRIST_LEFT + 1 ) ,
NUI_SKELETON_POSITION_SHOULDER_RIGHT	= ( NUI_SKELETON_POSITION_HAND_LEFT + 1 ) ,
NUI_SKELETON_POSITION_ELBOW_RIGHT	= ( NUI_SKELETON_POSITION_SHOULDER_RIGHT + 1 ) ,
NUI_SKELETON_POSITION_WRIST_RIGHT	= ( NUI_SKELETON_POSITION_ELBOW_RIGHT + 1 ) ,
NUI_SKELETON_POSITION_HAND_RIGHT	= ( NUI_SKELETON_POSITION_WRIST_RIGHT + 1 ) ,
NUI_SKELETON_POSITION_HIP_LEFT	= ( NUI_SKELETON_POSITION_HAND_RIGHT + 1 ) ,
NUI_SKELETON_POSITION_KNEE_LEFT	= ( NUI_SKELETON_POSITION_HIP_LEFT + 1 ) ,
NUI_SKELETON_POSITION_ANKLE_LEFT	= ( NUI_SKELETON_POSITION_KNEE_LEFT + 1 ) ,
NUI_SKELETON_POSITION_FOOT_LEFT	= ( NUI_SKELETON_POSITION_ANKLE_LEFT + 1 ) ,
NUI_SKELETON_POSITION_HIP_RIGHT	= ( NUI_SKELETON_POSITION_FOOT_LEFT + 1 ) ,
NUI_SKELETON_POSITION_KNEE_RIGHT	= ( NUI_SKELETON_POSITION_HIP_RIGHT + 1 ) ,
NUI_SKELETON_POSITION_ANKLE_RIGHT	= ( NUI_SKELETON_POSITION_KNEE_RIGHT + 1 ) ,
NUI_SKELETON_POSITION_FOOT_RIGHT	= ( NUI_SKELETON_POSITION_ANKLE_RIGHT + 1 ) ,
NUI_SKELETON_POSITION_COUNT	= ( NUI_SKELETON_POSITION_FOOT_RIGHT + 1 )
} 	NUI_SKELETON_POSITION_INDEX;
#endif
#endif

#ifdef _ARLK_NITE_
#ifndef _NUI_SKELETON_POSITION_INDEX_NITE_
#define _NUI_SKELETON_POSITION_INDEX_NITE_
typedef
	enum _NUI_SKELETON_POSITION_INDEX
{
	NUI_SKELETON_POSITION_HEAD	= 0,
	NUI_SKELETON_POSITION_SHOULDER_CENTER = 1,
	NUI_SKELETON_POSITION_SHOULDER_LEFT	= 2,
	NUI_SKELETON_POSITION_ELBOW_LEFT	= 3 ,
	NUI_SKELETON_POSITION_WRIST_LEFT	= 4 ,
	NUI_SKELETON_POSITION_SHOULDER_RIGHT	= 5 ,
	NUI_SKELETON_POSITION_ELBOW_RIGHT	= 6 ,
	NUI_SKELETON_POSITION_WRIST_RIGHT	= 7 ,
	NUI_SKELETON_POSITION_SPINE	= 8 ,
	NUI_SKELETON_POSITION_HIP_LEFT	= 9 ,
	NUI_SKELETON_POSITION_KNEE_LEFT	= 10 ,
	NUI_SKELETON_POSITION_ANKLE_LEFT	= 11 ,
	NUI_SKELETON_POSITION_HIP_RIGHT	= 12 ,
	NUI_SKELETON_POSITION_KNEE_RIGHT	= 13 ,
	NUI_SKELETON_POSITION_ANKLE_RIGHT	= 14 ,
	NUI_SKELETON_POSITION_COUNT	= ( NUI_SKELETON_POSITION_ANKLE_RIGHT + 1 )
} 	NUI_SKELETON_POSITION_INDEX;
#endif
#endif
